import {mobileCards} from './model';

export class Data{
    mobileCover:mobileCards[] = [
        {
            id: 1,
            img: '/assets/1.1.jpg',
            imgDetail: '/assets/1.0.jpg',
            title: 'Apple 11 Nike Cover',
            price: "₹700",
            rating: "5★",
            availability: "In Stock",
            Brand : "DeCorty",
            Color : "White",
            Material : "Plastic Sponge",
            Theme : "Weight Free",
            Type : "Plain"
        },
        {
            id: 2,
            img: '/assets/2.1.jpg',
            imgDetail: '/assets/2.0.jpg',
            title: 'Oppo Cases/Cover',
            price: "₹530",
            rating: "3★",
            availability: "In Stock",
            Brand : "Silicon",
            Color : "Blue with White",
            Material : "Artificial Leather",
            Theme : "Hologram",
            Type : "Designer"
        },
        {
            id: 3,
            img: '/assets/3.1.jpg',
            imgDetail: '/assets/3.0.jpg',
            title: 'MI Redmi 9 Cases',
            price: "₹700",
            rating: "5★",
            availability: "In Stock",
            Brand : "Fiber",
            Color : "Army Green",
            Material : "Rubber",
            Theme : "Designer",
            Type : "Plastic"
        },
        {
            id: 4,
            img: '/assets/4.1.jpg',
            imgDetail: '/assets/4.0.jpg',
            title: 'Apple 14 Fiber Cases',
            price: "₹530",
            rating: "4★",
            availability: "No Stock",
            Brand : "Silicon",
            Color : "Red",
            Material : "Rubber",
            Theme : "Brand",
            Type : "Plain",
        },
        {
            id: 5,
            img: '/assets/5.1.jpg',
            imgDetail: '/assets/5.0.jpg',
            title: 'Vivo Y61 Cases',
            price: "₹700",
            rating: "5★",
            availability: "In Stock",
            Brand : "DeCorty",
            Color : "Blue",
            Material : "Plastic",
            Theme : "Pookey Stickers",
            Type : "Doodle"
        },
        {
            id: 6,
            img: '/assets/6.1.jpg',
            imgDetail: '/assets/6.0.jpg',
            title: 'Korean Case Store',
            price: "₹530",
            rating: "5★",
            availability: "No Stock",
            Brand : "Leather",
            Color : "Pale Green",
            Material : "TPU",
            Theme : "Plain",
            Type : "Silicon Glass"
        },
        {
            id: 7,
            img: '/assets/7.1.jpg',
            imgDetail: '/assets/7.0.jpg',
            title: 'Apple 13 Pro Max Cases',
            price: "₹700",
            rating: "3★",
            availability: "In Stock",
            Brand : "Others",
            Color : "Pale Black",
            Material : "Silicon Glass",
            Theme : "3D",
            Type : "Designer"
        },
        {
            id: 8,
            img: '/assets/8.1.jpg',
            imgDetail: '/assets/8.0.jpg',
            title: 'Apple 11 Pro Max Cases',
            price: "₹530",
            rating: "5★",
            availability: "In Stock",
            Brand : "Fiber",
            Color : "Pace White",
            Material : "Rubber",
            Theme : "Hologram",
            Type : "Designer"
            
        },
        {
            id: 9,
            img: '/assets/9.1.jpg',
            imgDetail: '/assets/9.0.jpg',
            title: 'OPPO A31 Cases',
            price: "₹700",
            rating: "2★",
            availability: "In Stock",
            Brand : "Fiber",
            Color : "Pace yellow",
            Material : "Rubber",
            Theme : "Hologram",
            Type : "Designer"
        },
        {
            id: 10,
            img: '/assets/10.1.jpg',
            imgDetail: '/assets/10.0.jpg',
            title: 'Apple 15 Pro Max Cases',
            price: "₹530",
            rating: "4★",
            availability: "In Stock",
            Brand : "Fiber",
            Color : "Pace Grey",
            Material : "Rubber",
            Theme : "Hologram",
            Type : "Designer"
        }
    ]
}
